# Generated by Django 4.2.7 on 2023-11-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_auto_20231103_0809"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="phone_number",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
