# Generated by Django 4.2.7 on 2023-11-28 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0002_auto_20231006_0948"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
