# Generated by Django 4.2.7 on 2023-11-27 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_auto_20231028_0721"),
        ("orders", "0002_remove_orderproduct_color_remove_orderproduct_size"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderproduct",
            name="variation",
        ),
        migrations.AddField(
            model_name="orderproduct",
            name="variations",
            field=models.ManyToManyField(blank=True, to="store.variation"),
        ),
    ]
