# Generated by Django 4.2.7 on 2023-11-27 10:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_remove_orderproduct_variation_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderproduct",
            old_name="Payment",
            new_name="payment",
        ),
    ]
